
version: "3"
services:
  ptapiserver:
    build: .
    restart: always
    image: "bezahlonline/ptapiserver"
    ports:
      - "8060:8060"
    volumes:
      - /var/log/zvt:/var/log/zvt
    extra_hosts:
      - "pt:${PT_ADDR}"
