
version: "3"
services:
  ptapiserver:
    build: .
    restart: always
    image: "www.greisslomat.at:3307/ptapi:${PTAPI_VERSION}"
    ports:
      - "8060:8060"
    volumes:
      - /var/log/zvt:/var/log/zvt
    extra_hosts:
      - "pt:${PT_ADDR}"
