// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Status defines model for status.
type Status struct {

	// Status code
	Code int32 `json:"code"`

	// Status message
	Message string `json:"message"`
}

// Statusresponse defines model for statusresponse.
type Statusresponse Status
