openapi: '3.0.1'
info:
  version: '0.1.0'
  title: PTAPI
  description: Payment Device API

servers:
  - url: http://localhost:8060


paths:
  /test:
    get:
      description: Returns OK
      responses:
        '200':
          $ref: '#/components/responses/statusresponse'
          
  /authorise:
    post:
      operationId: authorise
      requestBody:
        description: >-
          initiate payment authorisation; api will log intemediate messages from PT;
          after initiation the authorisation_competion must be polled until the
          return result indicates either success or abortion of the process
        content:
          application/json:
            schema:
              type: object
              properties:
                receipt_code:
                  type: string
                  example: "00012021012713032101"
                amount:
                  description: amount in cent
                  type: integer
                  format: int64
                  example: 2790
              required:
                - amount
                - receipt_code
      responses:
        '200':
          $ref: '#/components/responses/statusresponse'
        '400':
          $ref: '#/components/responses/statusresponse'
          
  /abort:
    post:
      operationId: abort
      # requestBody:
      #   description: >-
      #     aborts running authorisation process
      #   content:
      #     application/json:
      #       schema:
      #         type: object
      #         properties:
      #           receipt_code:
      #             type: string
      #             example: "00012021012713032101"

      responses:
        '200':
          $ref: '#/components/responses/statusresponse'
        '400':
          $ref: '#/components/responses/statusresponse'

        
  /authorise_completion:
     post:
      operationId: AuthoriseCompletion
      requestBody:
        description: >-
          use to poll PT until completion of the finished
        content:
          application/json:
            schema:
              type: object
              properties:
                receipt_code:
                  type: string
                  example: "00012021012713032101"
              required:
                - receipt_code
      responses:
        '200':
          description: response of successful initiation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_completion_response'
        '400':
          $ref: '#/components/responses/statusresponse'

  /endofday:
    post:
      operationId: EndOfDay
      description: >-
        initiate end of day; api will log intemediate messages from PT;
        after initiation the endofday_competion must be polled until the
        return result indicates either success or abortion of the process
      responses:
        '200':
          $ref: '#/components/responses/statusresponse'
        '400':
          $ref: '#/components/responses/statusresponse'
          
               
  /endofday_completion:
    post:
      operationId: EndOfDayCompletion
      description: >-
        use to poll PT until completion of the finished
      responses:
        '200':
          description: response of successful initiation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/end_of_day_completion_response'
        '400':
          $ref: '#/components/responses/statusresponse'
                                
components:

  responses:
    statusresponse:
      description: status message with status code and message 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/status'
            
   
  schemas:
    status:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Status code
        message:
          type: string
          description: Status message

    card:
      type: object
      properties:
        sequence_nr:
          type: integer
          format: int32
          example: 1
        type:
          type: integer
          format: int32
          example: 0
        name:
          type: string
          example: 0
        pan_ef_id:
          type: string
          example: '**** *** **** 5726'
      required:
        - name
        - type
        - pan_ef_id
        - sequence_nr

    authorise_response:
      type: object
      properties:
        error:
          type: string
          example: "timeout"
        result:
          $ref: '#/components/schemas/authorise_result'
        data:
          $ref: '#/components/schemas/authorise_response_data'
      required:
        - error
        - result
    
    authorise_result:
      type: string
      enum:
        - 'pending'
        - 'success'
        - 'timeout'
        - 'abort'

    authorise_response_data:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          example: 2790
        currency:
          type: integer
          format: int32
          example: 123
        timestamp:
          type: string
          example: '20210310 094833'
        terminal_id:
          type: string
          example: '29001006'
        vu_nr:
          type: string
          example: '100764992'
        receipt_nr:
          type: integer
          format: int64
          example: '0022'
        turnover_nr:
          type: integer
          format: int64
          example: '0022'
        card_tech:
          type: integer
          format: int32
          example: 2
        aid:
          type: string
          example: 'A0000000041010'
        info:
          type: string
          example: 'Karte abgelehnt'
        crypto:
          type: string
          example: 'CC0D7CBD9E02A2A'
        card:
          $ref: '#/components/schemas/card'
      required:
        - receipt_nr
        - turnover_nr
        - crypto
        - card
        - vu_nr
        - terminal_id
        - amount
        - timestamp
        - currency
        - info

    auth_completion_response:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 1
        message:
          type: string
          example: 'please wait'
        transaction:
          $ref: '#/components/schemas/authorise_response'
      required:
        - status
        - message
        
    end_of_day_completion_response:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 1
        message:
          type: string
          example: 'please wait'
        transaction:
          $ref: '#/components/schemas/end_of_day_response'
      required:
        - status
        - message
        
    end_of_day_response:
      type: object
      properties:
        error:
          type: string
          example: "timeout"
        result:
          $ref: '#/components/schemas/end_of_day_result'
        data:
          $ref: '#/components/schemas/end_of_day_response_data'
      required:
        - error
        - result
    
    end_of_day_result:
      type: string
      enum:
        - 'pending'
        - 'success'
        - 'timeout'
        - 'abort'

    end_of_day_response_data:
      type: object
      properties:
        tracenr:
          type: integer
          format: int64
          example: 1234
        date:           
          type: string
          example:   "3103"          
        time:           
          type: string
          example: "170521"
        total:           
          type: integer
          format: int64
          example: 12340
        single_totals:
          $ref: '#/components/schemas/single_totals'
      required:
        - tracenr
        - date    
        - time      
        - total
        - single_totals
              
    single_totals:
      type: object
      properties:
        ReceiptNrStart:
          type: integer
          format: int64
          example: 68
        ReceiptNrEnd:  
          type: integer
          format: int64
          example: 71
        CountEC:       
          type: integer
          format: int64
          example: 4
        TotalEC:       
          type: integer
          format: int64
          example: 2600
        CountJCB:      
          type: integer
          format: int64
          example: 0
        TotalJCB:      
          type: integer
          format: int64
          example: 0
        CountEurocard: 
          type: integer
          format: int64
          example: 0
        TotalEurocard: 
          type: integer
          format: int64
          example: 0
        CountAmex:     
          type: integer
          format: int64
          example: 0
        TotalAmex:     
          type: integer
          format: int64
          example: 0
        CountVisa:     
          type: integer
          format: int64
          example: 0
        TotalVisa:     
          type: integer
          format: int64
          example: 0
        CountDiners:   
          type: integer
          format: int64
          example: 0
        TotalDiners:   
          type: integer
          format: int64
          example: 0
        CountOther:    
          type: integer
          format: int64
          example: 0
        TotalOther:    
          type: integer
          format: int64
          example: 0
