// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// AuthoriseResponse defines model for authorise_response.
type AuthoriseResponse struct {
	Data   *AuthoriseResponseData `json:"data,omitempty"`
	Error  string                 `json:"error"`
	Result AuthoriseResult        `json:"result"`
}

// AuthoriseResponseData defines model for authorise_response_data.
type AuthoriseResponseData struct {
	Aid        *string `json:"aid,omitempty"`
	Amount     int64   `json:"amount"`
	Card       Card    `json:"card"`
	CardTech   *int32  `json:"card_tech,omitempty"`
	Crypto     string  `json:"crypto"`
	ReceiptNr  int64   `json:"receipt_nr"`
	TerminalId string  `json:"terminal_id"`
	Timestamp  string  `json:"timestamp"`
	TurnoverNr int64   `json:"turnover_nr"`
	VuNr       string  `json:"vu_nr"`
}

// AuthoriseResult defines model for authorise_result.
type AuthoriseResult string

// List of AuthoriseResult
const (
	AuthoriseResult_abort   AuthoriseResult = "abort"
	AuthoriseResult_pending AuthoriseResult = "pending"
	AuthoriseResult_success AuthoriseResult = "success"
	AuthoriseResult_timeout AuthoriseResult = "timeout"
)

// Card defines model for card.
type Card struct {
	Name       string `json:"name"`
	PanEfId    string `json:"pan_ef_id"`
	SequenceNr int32  `json:"sequence_nr"`
	Type       int32  `json:"type"`
}

// CompletionResponse defines model for completion_response.
type CompletionResponse struct {
	Message     string             `json:"message"`
	Status      int32              `json:"status"`
	Transaction *AuthoriseResponse `json:"transaction,omitempty"`
}

// Status defines model for status.
type Status struct {

	// Status code
	Code int32 `json:"code"`

	// Status message
	Message string `json:"message"`
}

// Statusresponse defines model for statusresponse.
type Statusresponse Status

// AuthoriseJSONBody defines parameters for Authorise.
type AuthoriseJSONBody struct {

	// amount in cent
	Amount      int64   `json:"amount"`
	ReceiptCode *string `json:"receipt_code,omitempty"`
}

// AuthoriseCompletionJSONBody defines parameters for AuthoriseCompletion.
type AuthoriseCompletionJSONBody struct {
	ReceiptCode string `json:"receipt_code"`
}

// AuthoriseJSONRequestBody defines body for Authorise for application/json ContentType.
type AuthoriseJSONRequestBody AuthoriseJSONBody

// AuthoriseCompletionJSONRequestBody defines body for AuthoriseCompletion for application/json ContentType.
type AuthoriseCompletionJSONRequestBody AuthoriseCompletionJSONBody
